[setup]
runtime = "nodejs_20"

[install]
# Custom install commands (optional)
commands = [
  "corepack enable",
  "corepack prepare yarn@stable --activate"
]

[build]
# Custom build command
commands = [
  "yarn install --check-cache",
  "yarn run build"
]

[start]
# Custom start command
commands = [
  "yarn run start"
]
