[setup]
runtime = "nodejs_20"

[install]
commands = [
  "corepack enable",
  "corepack prepare yarn@stable --activate",
  "yarn install"
]

[build]
commands = [
  "yarn run build"
]

[start]
commands = [
  "yarn run start"
]
