[project]
id = "com.example.my-app"
name = "My Node.js App"
version = "1.0.0"

[[build.env]]
name = "BP_NODE_VERSION"
value = "20.*"  # Use Node.js 20.x

[[build.env]]
name = "BP_NPM_INSTALL_OPTS"
value = "--legacy-peer-deps"  # Optional: Adjust npm install options if needed
